"use client";

import { useState, useEffect, FormEvent } from 'react';
import { useParams, useRouter } from 'next/navigation';
import api from '@/lib/axios';

interface RequestDetail {
    id: string;
    fullName: string;
    universityName: string;
    degreeTitle: string;
    registrationNo: string;
    degreeDoc: string;
    transcriptDoc: string;
    passportDoc: string;
    status: string;
}

export default function AdminUploadReport() {
    const { id } = useParams();
    const router = useRouter();
    const [request, setRequest] = useState<RequestDetail | null>(null);
    const [reportUrl, setReportUrl] = useState('');
    const [loading, setLoading] = useState(true);
    const [submitting, setSubmitting] = useState(false);

    useEffect(() => {
        fetchRequestDetail();
    }, [id]);

    const fetchRequestDetail = async () => {
        try {
            const token = localStorage.getItem('token');
            // Hum admin all requests se filter kar sakte hain ya direct detail API bana sakte hain
            const res = await api.get('/verification/admin/all', {
                headers: { Authorization: `Bearer ${token}` }
            });
            const found = res.data.find((r: RequestDetail) => r.id === id);
            setRequest(found);
        } catch (err) {
            console.error("Error fetching detail", err);
        } finally {
            setLoading(false);
        }
    };

    const handleUpload = async (e: FormEvent) => {
        e.preventDefault();
        setSubmitting(true);
        try {
            const token = localStorage.getItem('token');
            await api.put(`/verification/admin/upload/${id}`, {
                verifiedReportUrl: reportUrl,
                status: 'COMPLETED'
            }, {
                headers: { Authorization: `Bearer ${token}` }
            });
            alert("Report Uploaded & Status Completed!");
            router.push('/admin/dashboard');
        } catch (err) {
            alert("Upload failed!");
        } finally {
            setSubmitting(false);
        }
    };

    if (loading) return <div className="p-10 text-center text-black font-sans">Loading details...</div>;
    if (!request) return <div className="p-10 text-center text-red-500">Request not found.</div>;

    return (
        <div className="min-h-screen bg-gray-50 p-6 font-sans">
            <div className="max-w-5xl mx-auto">
                <button onClick={() => router.back()} className="mb-4 text-blue-600 font-semibold hover:underline">
                    ← Back to Dashboard
                </button>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Left: Student Details & Documents */}
                    <div className="bg-white p-6 rounded-xl shadow-md">
                        <h2 className="text-xl font-bold mb-4 text-gray-800 border-b pb-2">Student Information</h2>
                        <div className="space-y-3 text-black">
                            <p><strong>Name:</strong> {request.fullName}</p>
                            <p><strong>University:</strong> {request.universityName}</p>
                            <p><strong>Degree:</strong> {request.degreeTitle}</p>
                            <p><strong>Reg No:</strong> {request.registrationNo}</p>
                        </div>

                        <h2 className="text-xl font-bold mt-8 mb-4 text-gray-800 border-b pb-2">Documents Submitted</h2>
                        <div className="grid grid-cols-1 gap-4">
                            <a href={request.degreeDoc} target="_blank" className="p-3 bg-blue-50 text-blue-700 rounded-lg text-center font-medium border border-blue-200">View Degree Doc</a>
                            <a href={request.transcriptDoc} target="_blank" className="p-3 bg-blue-50 text-blue-700 rounded-lg text-center font-medium border border-blue-200">View Transcript</a>
                            <a href={request.passportDoc} target="_blank" className="p-3 bg-blue-50 text-blue-700 rounded-lg text-center font-medium border border-blue-200">View Passport</a>
                        </div>
                    </div>

                    {/* Right: Admin Action Area */}
                    <div className="bg-white p-6 rounded-xl shadow-md border-t-4 border-green-500">
                        <h2 className="text-xl font-bold mb-4 text-gray-800">Verify & Complete</h2>
                        <p className="text-sm text-gray-600 mb-6">Enter the URL of the final verified report (PDF) generated by the system.</p>

                        <form onSubmit={handleUpload} className="space-y-4">
                            <div>
                                <label className="block text-sm font-bold text-gray-700 mb-2">Verified Report URL</label>
                                <input
                                    type="text"
                                    required
                                    value={reportUrl}
                                    onChange={(e) => setReportUrl(e.target.value)}
                                    placeholder="https://cloudinary.com/verified-report.pdf"
                                    className="w-full p-3 border rounded-lg outline-none focus:ring-2 focus:ring-green-500 text-black"
                                />
                            </div>

                            <button
                                type="submit"
                                disabled={submitting}
                                className={`w-full p-3 rounded-lg text-white font-bold transition-all ${submitting ? 'bg-gray-400' : 'bg-green-600 hover:bg-green-700'}`}
                            >
                                {submitting ? 'Updating System...' : 'Mark as Verified & Complete'}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    );
}